"""empty message

Revision ID: 47ffc0753134
Revises: 
Create Date: 2021-10-17 15:56:13.694830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ffc0753134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_title', sa.String(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_data')
    # ### end Alembic commands ###
